FROM node:20-alpine

WORKDIR /app
COPY package.json yarn.lock ./

RUN yarn

COPY tailwind.config.ts .eslintrc.json tsconfig.json next.config.mjs postcss.config.mjs ./

COPY ./src ./src
EXPOSE 3000

RUN yarn build

CMD yarn start

