name: "Get Short SHA for Tag"
description: "Output a truncated github sha to use for tagging"
outputs:
  short-sha:
    description: "The truncated string"

runs:
  using: "composite"
  steps:
    - name: Shorten SHA
      id: shorten-sha
      shell: bash
      run: |
        SHORT_SHA=(echo ${{ github.sha }} | cut -c 1-9)
        echo "short-sha=$SHORT_SHA" >> "$GITHUB_OUTPUT"