
name: Build to Amazon ECR

on:
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-cuttle-next:
    name: Build CuttleNext Docker Image 
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.set-cuttlenet-tag-name.outputs.tag }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build --file Dockerfile --tag ${{ secrets.AWS_ECR_REPO }}:$GITHUB_SHA .
      - name: Save Docker image as an artifact
        run: docker save ${{ secrets.AWS_ECR_REPO }}:$GITHUB_SHA | gzip > image.tar.gz
      - name: Upload Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: image.tar.gz

  deploy-cuttle-next:
    name: Deploy CuttleNext Image 
    runs-on: ubuntu-latest
    needs: build-cuttle-next
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
      - name: Load Docker image
        run: docker load < $GITHUB_WORKSPACE/image.tar.gz
      - name: Setup AWS ECR Details
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Login to Amazon ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Tag Docker image
        env:
          REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          REGISTRY_ALIAS: l5b5t6e6
          REPOSITORY: cuttlenet/cuttle-next
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag ${{ secrets.AWS_ECR_REPO }}:$GITHUB_SHA \
          $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
      - name: Push Docker image to ECR
        env:
          IMAGE_TAG: ${{ github.sha }}
          REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          REGISTRY_ALIAS: l5b5t6e6
          REPOSITORY: cuttlenet/cuttle-next
        run: docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
