
name: Build Cuttle-Next Image

on:
  push:
  pull_request:
    types:
      - synchronized
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  build-cuttle-next:
    name: Build CuttleNext Docker Image 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Create Tag Label for Build
        id: shorten-sha
        uses: FURams09/cuttlenet-actions/.github/actions/get-short-sha@v1
      - name: Build the Docker image
        run: docker build --file Dockerfile --tag ${{ vars.AWS_ECR_REPO }}:${{ steps.shorten-sha.outputs.short-sha }} .
      - name: Save Docker image as an artifact
        run: docker save -o cuttle-next-image.tar ${{ vars.AWS_ECR_REPO }}:${{ steps.shorten-sha.outputs.short-sha }}
        if: github.ref == 'refs/heads/main'
      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cuttle-next-latest
          path: cuttle-next-image.tar
          overwrite: true
  deploy-cuttle-next:
    name: Deploy CuttleNext Image 
    runs-on: ubuntu-latest
    needs: build-cuttle-next
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: cuttle-next-latest
      - name: Load Docker image
        run: docker load < $GITHUB_WORKSPACE/cuttle-next-image.tar
      - name: Setup AWS ECR Details
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{vars.AWS_REGION}}
      - name: Login to Amazon ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Get SHA Tag
        id: shorten-sha
        uses: FURams09/cuttlenet-actions/.github/actions/get-short-sha@v1
      - name: Tag Docker image
        env:
          REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          REPOSITORY: cuttlenet/cuttle-next
          IMAGE_TAG: latest
        run: |
          docker tag ${{ vars.AWS_ECR_REPO }}:${{ steps.shorten-sha.outputs.short-sha }} \
          $REGISTRY/${{ vars.AWS_ECR_REPO }}:$IMAGE_TAG
      - name: Push Docker image to ECR
        env:
          IMAGE_TAG: latest
          REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
        run: docker push $REGISTRY/${{ vars.AWS_ECR_REPO }}:$IMAGE_TAG
