
name: Build Cuttle-Next Image

on:
  push:
  pull_request:
    types:
      - opened
      - synchronized
      - closed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-cuttle-next:
    name: Build CuttleNext Docker Image 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Create Tag Label for Build
        id: shorten-sha
        uses: ./.github/actions/get-short-sha
      - name: Build the Docker image
        run: |
        echo "${{ steps.shorten-sha.outputs.short-sha }}"
        docker build --file Dockerfile --tag ${{ vars.AWS_ECR_REPO }}:${{ steps.shorten-sha.outputs.short-sha }} .
  upload-cuttle-next-artifact:
    name: Upload Artifact (main only)
    runs-on: ubuntu-latest
    needs: build-cuttle-next
    if: github.event.pull_request.merged == true
    steps:
      - name: Get SHA Tag
        id: shorten-sha
        uses: ./.github/actions/get-short-sha
      - name: Save Docker image as an artifact
        run: docker save -o cuttle-next-image.tar ${{ vars.AWS_ECR_REPO }}:${{ steps.shorten-sha.outputs.short-sha }}
      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cuttle-next-latest
          path: cuttle-next-image.tar
          overwrite: true