
name: Build to Amazon ECR

on:
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-cuttle-next:
    name: Build CuttleNext Docker Image 
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.set-cuttlenet-tag-name.outputs.tag }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag cuttle-next:$(date +%s)

  deploy-cuttle-next:
    name: Deploy CuttleNext Image 
    runs-on: ubuntu-latest
    steps:
      - name: Setup AWS ECR Details
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Login to Amazon ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Set Tag Hash
        id: set-cuttlenet-tag-name
        run: echo "tag=$(date +%s)-latest" >> "$GITHUB_OUTPUT"
      - name: Build and push the tagged docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO}}
          IMAGE_TAG: ${{ steps.set-cuttlenet-tag-name.outputs.tag}}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG